# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
  namespace: default
spec:
  selector:
    app: k8s-web-to-nginx
  type: LoadBalancer
  ports:
  - name: k8s-web-to-nginx
    protocol: TCP
    port: 3333
    targetPort: 3000
---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx
  namespace: default
  labels:
    app: k8s-web-to-nginx
spec:
  selector:
    matchLabels:
      app: k8s-web-to-nginx
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  k8s-web-to-nginx
      labels:
        app: k8s-web-to-nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: k8s-web-to-nginx
        image: rinarudhei/k8s-web-to-nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
---

